### ISSUE TITLE
Failed to add Android platform

### ISSUE THREAD

**Issue by bafu** [numbersprotocol/lifebox-legacy#7]
**Steps to Reproduce**

```
$ npm install -g cordova@8.1.2 ionic@4.10.2 
$ cd lifebox
$ npm install
$ ionic cordova platform add android
...
Installing "cordova-plugin-mauron85-background-geolocation" for android                                                                     
Error during processing of action! Attempting to revert...                                                                                  
Failed to install 'cordova-plugin-mauron85-background-geolocation': CordovaError: Uh oh!                                                    
"/home/bafu/codes/lifebox/platforms/android/app/src/main/java/com/marianhello/bgloc/cordova/ConfigMapper.java" already exists!              
    at copyNewFile (/home/bafu/codes/lifebox/platforms/android/cordova/lib/pluginHandlers.js:234:45)                                        
    at install (/home/bafu/codes/lifebox/platforms/android/cordova/lib/pluginHandlers.js:34:17)                                             
    at ActionStack.process (/home/bafu/codes/lifebox/node_modules/cordova-common/src/ActionStack.js:56:25)                                  
    at PluginManager.doOperation (/home/bafu/codes/lifebox/node_modules/cordova-common/src/PluginManager.js:114:20)                         
    at PluginManager.addPlugin (/home/bafu/codes/lifebox/node_modules/cordova-common/src/PluginManager.js:144:17)                           
    at /home/bafu/codes/lifebox/platforms/android/cordova/Api.js:212:74                                                                     
    at _fulfilled (/home/bafu/codes/lifebox/node_modules/q/q.js:854:54)                                                                     
    at /home/bafu/codes/lifebox/node_modules/q/q.js:883:30                                                                                  
    at Promise.promise.promiseDispatch (/home/bafu/codes/lifebox/node_modules/q/q.js:816:13)                                                
    at /home/bafu/codes/lifebox/node_modules/q/q.js:877:14                                                                                  
Uh oh!                                                                                                                                      
"/home/bafu/codes/lifebox/platforms/android/app/src/main/java/com/marianhello/bgloc/cordova/ConfigMapper.java" already exists!              
...
```

Please check `log-platform-add-android.txt` for more details.

**Logs**

* [log-npm-install.txt](https://github.com/numbersprotocol/lifebox/files/4365161/log-npm-install.txt)
* [log-platform-add-android.txt](https://github.com/numbersprotocol/lifebox/files/4365162/log-platform-add-android.txt)

**Environment**

lifebox: `v0.1.10`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

$ nodejs --version
v10.19.0

$ npm --version
6.13.4

$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/bafu/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.13.4
   OS                : Linux 4.19
```

**Comment by CS6** [comment]
`cordova-plugin-mauron85-background-geolocation
`
這一包我在新開的專案是裝不起來 (edited) 


所以我是參考 [ionic-4-turn-on-device-gps-in-ionic-4-application](https://webcache.googleusercontent.com/search?q=cache:_N3XfpB7mawJ:https://www.freakyjolly.com/ionic-4-turn-on-device-gps-in-ionic-4-application-without-leaving-app-using-ionic-native-plugin/+&cd=5&hl=zh-TW&ct=clnk&gl=tw)

```
 import { AndroidPermissions } from '@ionic-native/android-permissions/ngx';
import { LocationAccuracy } from '@ionic-native/location-accuracy/ngx';
```
至於不論是 Lifebox 還是我另外開的5.0專案，這兩個套件安裝都沒問題



我的環境
```
Ionic:
   Ionic CLI                     : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)
Utility:
   cordova-res (update available: 0.10.0) : 0.9.0
   native-run                             : 0.3.0
System:
   Android SDK Tools : 26.1.1 (/Users/sddivid/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.13.0 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by bafu** [comment]
Upgrade `ionic/cli` and `cordova` can not resolve this issue.

I got the same error: [log-platform-add-android.txt](https://github.com/numbersprotocol/lifebox/files/4365602/log-platform-add-android.txt)

**Environment**

```
$ ionic info 

Ionic:

   Ionic CLI                     : 6.3.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

Utility:

   cordova-res : 0.10.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/bafu/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.13.4
   OS                : Linux 4.19
```
